project_name: gowall

builds:
  - id: gowall
    main: ./gowall
    goos:
      - linux
      - darwin
      - windows
    ldflags: "-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}"
    env:
      - CGO_ENABLED=1

archives:
  - format: tar.gz
    files:
      - LICENSE
      - README.md

